version: '3.8'
services:
  vllm:
    image: vllm/vllm-openai:latest
    command: --model "/models/Llama-3.2-3B-Instruct-Frog" --quantization=bitsandbytes --api-key=token-abc123  --dtype=half --load_format=bitsandbytes --max_model_len=10000
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./model:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
